### ISSUE TITLE
请改'pad'为'scale'

### ISSUE THREAD

**Issue by 98mxr** [askerlee/rift#4]
在rife上实验时，经常发现视频黑边会严重干扰rife正常工作。
rift似乎对这个问题更加敏感了

当我用rift以0.5光流尺度推理时
![0000053](https://user-images.githubusercontent.com/82786769/155251530-1eb0ab50-1c7f-49a6-ab26-52ee02b8542b.png)

当我改变'pad'方法为'scale'方法处理原图片时，情况看起来得到了改善
![0000053](https://user-images.githubusercontent.com/82786769/155251617-5997663b-b7cd-4439-a6a8-7d0a1e525b9d.png)

`I1 = F.interpolate(I1, (ph, pw), mode='bilinear', align_corners=False)`
在inference_video.py的229和242行取代
`I1 = pad_image(I1)`

`mid = F.interpolate(mid, (h, w), mode='bilinear', align_corners=False)`
`mid = (((mid[0] * 255.).byte().cpu().numpy().transpose(1, 2, 0)))`
`write_buffer.put(mid)`
在inference_video.py的254-256行取代
`mid = (((mid[0] * 255.).byte().cpu().numpy().transpose(1, 2, 0)))`
`write_buffer.put(mid[:h, :w])`

**Comment by askerlee** [comment]
谢谢建议！很高兴已经有人用起来了。我已经按您的建议改进了code，下午会测试一下。

**Comment by askerlee** [comment]
原因应该是在padding的时候，算法算出黑边的flow为0，因为flow一般有某种平滑性，所以这些0 flow把边缘像素的flow推向0，导致artifact。

**Comment by 98mxr** [comment]
感谢反馈，还有一件小事就是，在我这边的测试中，最终结果的质量依旧很依赖于输入的scale值。似乎多尺度光流估计不能代替“自动光流尺度”这个功能。这个问题有可能得到解决吗

**Comment by askerlee** [comment]
谢谢提出这个问题。请问有没有效果不好的视频可以让我拿来测试呢？谢谢。

**Comment by 98mxr** [comment]
以下测试均为上图scale=0.5，下图scale=1.0

![0000005](https://user-images.githubusercontent.com/82786769/155436964-9042f9bb-a7c9-4019-982b-b12b537f9a0a.png)
![0000005](https://user-images.githubusercontent.com/82786769/155436973-e10c4089-ddc7-494d-a8ce-8169ef45db9e.png)

![0000013](https://user-images.githubusercontent.com/82786769/155437041-fbe13eea-3967-453f-86ec-8c1c048d43c1.png)
![0000013](https://user-images.githubusercontent.com/82786769/155437018-b95e9e7c-8c16-4caf-a421-75d507b574c6.png)

![0000021](https://user-images.githubusercontent.com/82786769/155437074-ceb1f0f3-f8b9-431c-af88-0351e97547ec.png)
![0000021](https://user-images.githubusercontent.com/82786769/155437084-929d3562-6325-43b1-a7b0-487497a3d511.png)

![0000029](https://user-images.githubusercontent.com/82786769/155437109-79d133cb-5c18-4bd4-9e35-2e3e5c6a91ae.png)
![0000029](https://user-images.githubusercontent.com/82786769/155437123-27cdb0de-03af-4976-b5dd-1ede7b5b2daf.png)

![0000037](https://user-images.githubusercontent.com/82786769/155437161-f11c70ed-8686-459d-be36-276c9fa6e2f3.png)
![0000037](https://user-images.githubusercontent.com/82786769/155437174-dd9eccdc-3c79-49b9-89ee-5e75364be87f.png)

测试用图片对，的1920*1080尺寸版本在这里
[https://drive.google.com/file/d/1cR115RIRhT2Nrk_Qz7rV2XRPeZfjbMNM/view?usp=sharing](url)

（可惜我显存不够只能跑720p版本，连scale=0.25因为pad原因都会炸显存
